# Generated by Django 2.0.5 on 2018-09-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrequests',
            unique_together={('request_by', 'accepted_by')},
        ),
    ]
