# Generated by Django 2.0.5 on 2018-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180917_1706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrequests',
            unique_together=set(),
        ),
    ]
